# Generated by Django 4.0.4 on 2022-05-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_alter_employee_uuid'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In-Process', 'In-Process')], max_length=30)),
                ('slug', models.SlugField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
                ('ref_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.employee')),
            ],
            options={
                'ordering': ('-updated_at', 'applicant', 'ref_emp'),
                'unique_together': {('job', 'ref_emp', 'applicant')},
            },
        ),
    ]
