# Generated by Django 4.0.4 on 2022-05-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referrals', '0002_remove_referral_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
