# Generated by Django 4.0.4 on 2022-05-21 12:26

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
