# Generated by Django 4.0.4 on 2022-05-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('ITS', 'IT'), ('FIN', 'Finances'), ('ENG', 'Engineering')], max_length=5)),
                ('location', models.CharField(choices=[('IN-BAN', 'Bangalore, India'), ('US-TXS', 'Texas, USA'), ('KR-SEO', 'Seoul, South Korea')], max_length=16)),
                ('position_type', models.CharField(choices=[('INT', 'Intern'), ('FTE', 'Full-time')], max_length=3)),
                ('is_open', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=64)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-last_edit', 'department', 'location'),
                'unique_together': {('title', 'department', 'location', 'position_type')},
            },
        ),
    ]
